Deactivate 32bits builds because the ksuid library does not support those
⨯ release failed after 7m3s                error=failed to build for freebsd_386: exit status 1: # github.com/exograd/go-daemon/ksuid
Error: ../../../go/pkg/mod/github.com/exograd/go-daemon@v0.0.0-20221017152404-800adf39c12f/ksuid/ksuid.go:38:15: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to fmt.Sprintf (overflows)
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.18.2/x64/goreleaser' failed with exit code 1